name: CI/CD React App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run tests if any
      - name: Run tests
        run: npm test --if-present

      # Step 5: Build the project
      - name: Build the project
        run: npm run build

      # Step 6: Configure Git for deployment
      - name: Configure Git
        run: |
          git config --global user.name "Srinivas Tharun"
          git config --global user.email "srinivasyenugu383@gmail.com"

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run deploy
